### ISSUE TITLE
Fails to build on Windows 11 with Visual Studio 2022 Community

### ISSUE THREAD

**Issue by onlyone-hyphen** [inferflow/inferflow#20]
Step 1) Clone the repo
![image](https://github.com/inferflow/inferflow/assets/149725370/6b4b0ba0-b230-4506-af14-9533013fb62e)

Step 2) Open interflow.sln with Visual Studio 2022
![image](https://github.com/inferflow/inferflow/assets/149725370/1c4fb7c1-3bb6-402d-904f-8ba22c7f8dc0)

Step 3) Visual Studio asks to retarget, accept the defaults and click OK
![image](https://github.com/inferflow/inferflow/assets/149725370/025d8de2-2dfb-4a48-93f3-851d316200c4)

Step 4) Switch to release configuration
![image](https://github.com/inferflow/inferflow/assets/149725370/8145c045-2318-437b-9cbb-0f0a64503748)

Step 5) Build the solution
![image](https://github.com/inferflow/inferflow/assets/149725370/bd3e4918-ca7f-44c8-8736-4c69111ac401)

Step 6) Notice the errors, build fails
![image](https://github.com/inferflow/inferflow/assets/149725370/fc2e5ae1-88d0-4e19-8c4a-ec75039c5cd4)

Step 7) Notice the build folder is created, some items get built, the most of it has failed
![image](https://github.com/inferflow/inferflow/assets/149725370/fb85a845-a5c9-4943-b72e-d1584a982838)

![image](https://github.com/inferflow/inferflow/assets/149725370/ab80415e-8785-495d-9d14-44b824c1fb75)

The projects wont load, if i try to reload them:
![image](https://github.com/inferflow/inferflow/assets/149725370/6ea6f867-b244-4307-8a49-1f25746823d8)

![image](https://github.com/inferflow/inferflow/assets/149725370/1342f67f-38d4-4528-a6ee-aae3c791d677)

I get the following error

`The imported project "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\BuildCustomizations\CUDA 12.2.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\\BuildCustomizations\CUDA 12.2.props" is correct, and that the file exists on disk.  C:\Users\michael\Documents\GitHub\inferflow\build\vs_projects\inferflow\inferflow_common.vcxproj`

If i navigate to that folder, the file it's looking for does not exist
![image](https://github.com/inferflow/inferflow/assets/149725370/42007839-a448-4a96-9633-4fb1cbbc613f)

**Comment by onlyone-hyphen** [comment]
So that didn't work

I'm going to install the older version of the Windows SDK and try it without upgrading

![image](https://github.com/inferflow/inferflow/assets/149725370/80d83fcd-9c50-45fb-a0cf-2ee8e06545f4)

Delete, Reclone, start again, open sln
![image](https://github.com/inferflow/inferflow/assets/149725370/4dfb05c8-fa0f-4280-8dff-d51a0d28f57a)

Rebuild
![image](https://github.com/inferflow/inferflow/assets/149725370/05522fe7-62e3-4ed4-8ffe-28df7944fd5d)
What a surprise!

Okay, lets install this junk from 2017

As per: https://stackoverflow.com/questions/57795314/are-visual-studio-2017-build-tools-still-available-for-download
Download this: https://aka.ms/vs/15/release/vs_buildtools.exe

![image](https://github.com/inferflow/inferflow/assets/149725370/96c770f6-4b12-4ed5-aa63-f68b55a40950)

Now we have the old build tools installed
![image](https://github.com/inferflow/inferflow/assets/149725370/674fcd91-19f9-4cc6-86fc-be07e7cfb90d)

Lets try again. Delete. Reclone. Open VS. Rebuild.

Same issue...

To those struggling with SDK version, build tool version mismatch etc... Don't bother installing the correct versions. This doesn't work, regardless of the versions.

I give up...

**Comment by shumingshi** [comment]
Sorry for the inconvenience caused to you and thank you for opening this issue.

The build error in step-6 is because Visual Studio 2022 has stricter warning checking than Visual Studio 2017 (which is the version we are using). We are going to fix the warnings soon and make sure that the codes can be built successfully on Visual Studio 2022.

About the CUDA version mismatch issue. We are going to examine it and try to find a solution.

**Comment by onlyone-hyphen** [comment]
It sure was frustrating and I ended up formatting my laptop 😂 but don't apologise, its not your fault. I read your paper and you've done some great work. I can't wait to try this again once it's ready for the latest versions of Windows 11/ VS 2022 etc, good luck

**Comment by shumingshi** [comment]
Visual Studio 2022 projects have been uploaded to **build/vs2022_projects**. In order to open **inferflow.sln** with all projects being successfully loaded, please make sure that NVCC 12.2 is installed **after** Visual Studio 2022. If NVCC was installed before Visual Studio, you can simply reinstall it again.

Please note that:
1. Early versions of the CUDA Toolkit can be found [here](https://developer.nvidia.com/cuda-toolkit-archive).
2. If you are reinstalling NVCC, please choose the **custom** installation option and then choose **NOT** to install the driver by unchecking the "driver components" checkbox.

Good luck.

**Comment by onlyone-hyphen** [comment]
Thank you, I'll let you know shortly how I get on

**Comment by onlyone-hyphen** [comment]
![image](https://github.com/inferflow/inferflow/assets/149725370/2d126067-aa4c-4a07-8789-ada5d965ce03)
Very nice :)
![image](https://github.com/inferflow/inferflow/assets/149725370/d202eaaa-8018-4795-b148-2d0d8845c407)
I'm assuming you built this on Windows 10, no problem I can just retarget the Windows 11 SDK
![image](https://github.com/inferflow/inferflow/assets/149725370/6bff7976-c045-407e-a7ef-2fd2b171d32f)
![image](https://github.com/inferflow/inferflow/assets/149725370/e92586bb-e750-49ff-be25-ffcc82a88518)
![image](https://github.com/inferflow/inferflow/assets/149725370/12c3e13e-8062-4760-a986-a819fe431f14)

**Comment by eabase** [comment]
This sucks, what's the solution? 
I'm not gonna downgrade, these nvidia/MS dudes just gotta get their shit together.
