### ISSUE TITLE
Is there a plan to support deepseek-moe model?

### ISSUE THREAD

**Issue by cdliang11** [inferflow/inferflow#22]
Hi,
Is there a plan to support [deepseek-moe-16b-chat model](https://huggingface.co/deepseek-ai/deepseek-moe-16b-chat)?

**Comment by jcyk** [comment]
Thank you for your quetion! The support for MoE models such as deepseek-moe is indeed a top priority on our development agenda. We are planning to incorporate this feature soon. Stay tuned!

**Comment by jcyk** [comment]
The latest version of Inferflow now supports MoE models such as `mixtral_8x7b_instruct_v0.1` and `deepseek_moe_16b_base`. You can give it a try and we would greatly appreciate your feedback. 
Feel Free to open another issue if you encounter any problems!
