### ISSUE TITLE
Bachuan2 prompt template

### ISSUE THREAD

**Issue by chenglin** [inferflow/inferflow#33]
Model：Baichuan2 7B Chat
Input：tell me a 50 word story
Inferflow Service Log：
```
decoding_alg: , strategy_id: 4, temperature: 0.00
Encoder input text:
Decoder input text:

{<reserved_106>}
tell me a 50 word story{<reserved_107>}

query_id: 1, output_len: 165, is_end: true
```

`<reserved_106>` and `<reserved_107>` should not be surrounded with `{}`，but in file `inferlow_service.ini` they are surrounded with `{}`. Should I just delete `{}` from  `inferlow_service.ini` or it is expected remove it in the c++ code ?

baichuan2 prompt template is: `\n\n<reserved_106>\n{query}<reserved_107>\n`

**Comment by shumingshi** [comment]
Putting a string between "{" and "}" means that this string should be treated as a single token in tokenization. So {<reserved_106>} will be transformed to the token-id of "<reserved_106>" during prompt processing.
Therefore, the "{" and "}" in inferlow_service.ini should be kept.

**Comment by chenglin** [comment]
Got it. Thanks
