### ISSUE TITLE
Is support for the OpenAI REST API in your roadmap?

### ISSUE THREAD

**Issue by chenglin** [inferflow/inferflow#36]
We are using OpenAI REST API with vLLM. Will inferflow support OpenAI REST api later? So we can migrate to inferflow easier if inferflow is more performance than vLLM.

By the way, have yo do some performance comparison with vLLM or other LLM Inference Engine?

**Comment by huliangbing** [comment]
"When will support for the OpenAI API be available?"
Thanks!

**Comment by Whiplashzeb** [comment]
> "When will support for the OpenAI API be available?" Thanks!

We expect to add support for the OpenAI REST API in mid-March. Thank you for your patience.

**Comment by huliangbing** [comment]
加油！

**Comment by Whiplashzeb** [comment]
We already support the OpenAI API format

**Comment by huliangbing** [comment]
Thanks!
