### ISSUE TITLE
How to support a new model such as QWen?

### ISSUE THREAD

**Issue by Tint0ri** [inferflow/inferflow#43]
Hybrid inference looks like a game changer. I want test it on Qwen. But how to make the model_spec.json for Qwen 1.5?

Thanks.

**Comment by shumingshi** [comment]
The specification file of Qwen1.5-7B-Chat has been added to [data/models/qwen1.5_7b_chat](../tree/main/data/models/qwen1.5_7b_chat).
Please have a try. Other models in the Qwen1.5 series can be treated similarly. Please feel free to contact us for any additional questions.

**Comment by Tint0ri** [comment]
Thanks
